"""
Regenerate the colour keys of `.streamlit/config.toml` from `src/core/design_tokens.py`.

    python scripts/sync_streamlit_theme.py           # rewrite the generated block
    python scripts/sync_streamlit_theme.py --check   # exit 1 if the file is stale

The TOML cannot import Python, so it carries a generated copy of the palette.
Only the text between the BEGIN and END markers is rewritten; the fonts, radii
and every other setting in the file are left alone. A palette change is one
command, and `tests/test_theme_sync.py` fails if it is forgotten.

Streamlit's native widgets get ONE fixed theme: the Day palette, written as flat
`[theme]` keys. There are deliberately no `[theme.light]` / `[theme.dark]`
sections: with both present Streamlit picks its theme from the browser's colour
scheme, which the app's own Day/Night toggle cannot control, so a dark browser
showed dark-themed inputs and near-invisible captions on the Day page. Night mode
is the app's own CSS (`ui/styles.py`) on top of this fixed native theme.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.core.design_tokens import Mode, palette  # noqa: E402

CONFIG_PATH = ROOT / ".streamlit" / "config.toml"
BEGIN = "# BEGIN generated by scripts/sync_streamlit_theme.py. Do not edit by hand."
END = "# END generated"

#: Streamlit theme key -> design token name (see `design_tokens.TOKEN_ORDER`).
THEME_KEY_TOKENS: dict[str, str] = {
    "primaryColor": "pen",
    "backgroundColor": "stock",
    "secondaryBackgroundColor": "sheet_alt",
    "textColor": "ink",
    "dataframeBorderColor": "rule",
    "dataframeHeaderBackgroundColor": "sheet_alt",
}

#: The one palette Streamlit's native widgets use, whatever the browser prefers.
NATIVE_MODE: Mode = "day"


def render_block() -> str:
    """The generated text, markers included, ending with a newline."""
    tokens = palette(NATIVE_MODE)
    lines = [BEGIN]
    lines.extend(f'{key} = "{tokens[tok]}"' for key, tok in THEME_KEY_TOKENS.items())
    lines.append(END)
    return "\n".join(lines) + "\n"


def sync(text: str) -> str:
    """`text` with the generated block replaced. Raises if the markers are missing."""
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        raise ValueError(f"{CONFIG_PATH.name} is missing the BEGIN/END generated markers")
    end += len(END)
    if text[end : end + 1] == "\n":
        end += 1
    return text[:start] + render_block() + text[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args(argv)

    current = CONFIG_PATH.read_text(encoding="utf-8")
    updated = sync(current)
    if updated == current:
        print(f"{CONFIG_PATH.name} is up to date")
        return 0
    if args.check:
        print(f"{CONFIG_PATH.name} is stale; run python scripts/sync_streamlit_theme.py")
        return 1
    CONFIG_PATH.write_text(updated, encoding="utf-8")
    print(f"updated {CONFIG_PATH.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
